[project]
name = "password-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gomez Alan", email = "gomezpazalansamuel@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flask>=3.0",
    "pynacl>=1.5",
    "python-dotenv>=1.0",
]

[project.scripts]
password-manager = "password_manager:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
